server:
  port: 8180

spring:
  datasource:
    username: root
    password: mariapassword
    url: jdbc:mariadb://localhost:13307/cartdb
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
      encoding: utf-8
      mode: always
      continue-on-error: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
        format_sql: true
        enable_lazy_load_no_trans: true
    hibernate:
      # create: entityテーブルがあれば削除し、再生成を行う。
      # create-drop: entityテーブルがあれば削除し、再生成を行う。また、Springboot終了時にテーブルを削除する。
      # update: Entityのテーブルがない場合、作成する。
      ddl-auto: create-drop
    show-sql: true
